USE UFC;
INSERT INTO paises (nombre, dominio) VALUES
  ("Afganistán","AF"),
  ("Albania","AL"),
  ("Alemania","DE"),
  ("Andorra","AD"),
  ("Angola","AO"),
  ("Anguila","AI"),
  ("Antártida","AQ"),
  ("Antigua y Barbuda","AG"),
  ("Arabia Saudita","SA"),
  ("Argelia","DZ"),
  ("Argentina","AR"),
  ("Armenia","AM"),
  ("Aruba","AW"),
  ("Australia","AU"),
  ("Austria","AT"),
  ("Azerbaiyán","AZ"),
  ("Bélgica","BE"),
  ("Bahamas","BS"),
  ("Bahrein","BH"),
  ("Bangladesh","BD"),
  ("Barbados","BB"),
  ("Belice","BZ"),
  ("Benín","BJ"),
  ("Bhután","BT"),
  ("Bielorrusia","BY"),
  ("Birmania","MM"),
  ("Bolivia","BO"),
  ("Bosnia y Herzegovina","BA"),
  ("Botsuana","BW"),
  ("Brasil","BR"),
  ("Brunéi","BN"),
  ("Bulgaria","BG"),
  ("Burkina Faso","BF"),
  ("Burundi","BI"),
  ("Cabo Verde","CV"),
  ("Camboya","KH"),
  ("Camerún","CM"),
  ("Canadá","CA"),
  ("Chad","TD"),
  ("Chile","CL"),
  ("China","CN"),
  ("Chipre","CY"),
  ("Ciudad del Vaticano","VA"),
  ("Colombia","CO"),
  ("Comoras","KM"),
  ("República del Congo","CG"),
  ("República Democrática del Congo","CD"),
  ("Corea del Norte","KP"),
  ("Corea del Sur","KR"),
  ("Costa de Marfil","CI"),
  ("Costa Rica","CR"),
  ("Croacia","HR"),
  ("Cuba","CU"),
  ("Curazao","CW"),
  ("Dinamarca","DK"),
  ("Dominica","DM"),
  ("Ecuador","EC"),
  ("Egipto","EG"),
  ("El Salvador","SV"),
  ("Emiratos Árabes Unidos","AE"),
  ("Eritrea","ER"),
  ("Eslovaquia","SK"),
  ("Eslovenia","SI"),
  ("España","ES"),
  ("Estados Unidos de América","US"),
  ("Estonia","EE"),
  ("Etiopía","ET"),
  ("Filipinas","PH"),
  ("Finlandia","FI"),
  ("Fiyi","FJ"),
  ("Francia","FR"),
  ("Gabón","GA"),
  ("Gambia","GM"),
  ("Georgia","GE"),
  ("Ghana","GH"),
  ("Gibraltar","GI"),
  ("Granada","GD"),
  ("Grecia","GR"),
  ("Groenlandia","GL"),
  ("Guadalupe","GP"),
  ("Guam","GU"),
  ("Guatemala","GT"),
  ("Guayana Francesa","GF"),
  ("Guernsey","GG"),
  ("Guinea","GN"),
  ("Guinea Ecuatorial","GQ"),
  ("Guinea-Bissau","GW"),
  ("Guyana","GY"),
  ("Haití","HT"),
  ("Honduras","HN"),
  ("Hong kong","HK"),
  ("Hungría","HU"),
  ("India","IN"),
  ("Indonesia","ID"),
  ("Irán","IR"),
  ("Irak","IQ"),
  ("Irlanda","IE"),
  ("Isla Bouvet","BV"),
  ("Isla de Man","IM"),
  ("Isla de Navidad","CX"),
  ("Isla Norfolk","NF"),
  ("Islandia","IS"),
  ("Islas Bermudas","BM"),
  ("Islas Caimán","KY"),
  ("Islas Cocos (Keeling)","CC"),
  ("Islas Cook","CK"),
  ("Islas de Åland","AX"),
  ("Islas Feroe","FO"),
  ("Islas Georgias del Sur y Sandwich del Sur","GS"),
  ("Islas Heard y McDonald","HM"),
  ("Islas Maldivas","MV"),
  ("Islas Malvinas","FK"),
  ("Islas Marianas del Norte","MP"),
  ("Islas Marshall","MH"),
  ("Islas Pitcairn","PN"),
  ("Islas Salomón","SB"),
  ("Islas Turcas y Caicos","TC"),
  ("Islas Ultramarinas Menores de Estados Unidos","UM"),
  ("Islas Vírgenes Británicas","VG"),
  ("Islas Vírgenes de los Estados Unidos","VI"),
  ("Israel","IL"),
  ("Italia","IT"),
  ("Jamaica","JM"),
  ("Japón","JP"),
  ("Jersey","JE"),
  ("Jordania","JO"),
  ("Kazajistán","KZ"),
  ("Kenia","KE"),
  ("Kirguistán","KG"),
  ("Kiribati","KI"),
  ("Kuwait","KW"),
  ("Líbano","LB"),
  ("Laos","LA"),
  ("Lesoto","LS"),
  ("Letonia","LV"),
  ("Liberia","LR"),
  ("Libia","LY"),
  ("Liechtenstein","LI"),
  ("Lituania","LT"),
  ("Luxemburgo","LU"),
  ("México","MX"),
  ("Mónaco","MC"),
  ("Macao","MO"),
  ("Macedônia","MK"),
  ("Madagascar","MG"),
  ("Malasia","MY"),
  ("Malawi","MW"),
  ("Mali","ML"),
  ("Malta","MT"),
  ("Marruecos","MA"),
  ("Martinica","MQ"),
  ("Mauricio","MU"),
  ("Mauritania","MR"),
  ("Mayotte","YT"),
  ("Micronesia","FM"),
  ("Moldavia","MD"),
  ("Mongolia","MN"),
  ("Montenegro","ME"),
  ("Montserrat","MS"),
  ("Mozambique","MZ"),
  ("Namibia","NA"),
  ("Nauru","NR"),
  ("Nepal","NP"),
  ("Nicaragua","NI"),
  ("Niger","NE"),
  ("Nigeria","NG"),
  ("Niue","NU"),
  ("Noruega","NO"),
  ("Nueva Caledonia","NC"),
  ("Nueva Zelanda","NZ"),
  ("Omán","OM"),
  ("Países Bajos","NL"),
  ("Pakistán","PK"),
  ("Palau","PW"),
  ("Palestina","PS"),
  ("Panamá","PA"),
  ("Papúa Nueva Guinea","PG"),
  ("Paraguay","PY"),
  ("Perú","PE"),
  ("Polinesia Francesa","PF"),
  ("Polonia","PL"),
  ("Portugal","PT"),
  ("Puerto Rico","PR"),
  ("Qatar","QA"),
  ("Reino Unido","GB"),
  ("República Centroafricana","CF"),
  ("República Checa","CZ"),
  ("República Dominicana","DO"),
  ("República de Sudán del Sur","SS"),
  ("Reunión","RE"),
  ("Ruanda","RW"),
  ("Rumanía","RO"),
  ("Rusia","RU"),
  ("Sahara Occidental","EH"),
  ("Samoa","WS"),
  ("Samoa Americana","AS"),
  ("San Bartolomé","BL"),
  ("San Cristóbal y Nieves","KN"),
  ("San Marino","SM"),
  ("San Martín (Francia)","MF"),
  ("San Pedro y Miquelón","PM"),
  ("San Vicente y las Granadinas","VC"),
  ("Santa Elena","SH"),
  ("Santa Lucía","LC"),
  ("Santo Tomé y Príncipe","ST"),
  ("Senegal","SN"),
  ("Serbia","RS"),
  ("Seychelles","SC"),
  ("Sierra Leona","SL"),
  ("Singapur","SG"),
  ("Sint Maarten","SX"),
  ("Siria","SY"),
  ("Somalia","SO"),
  ("Sri lanka","LK"),
  ("Sudáfrica","ZA"),
  ("Sudán","SD"),
  ("Suecia","SE"),
  ("Suiza","CH"),
  ("Surinám","SR"),
  ("Svalbard y Jan Mayen","SJ"),
  ("Swazilandia","SZ"),
  ("Tayikistán","TJ"),
  ("Tailandia","TH"),
  ("Taiwán","TW"),
  ("Tanzania","TZ"),
  ("Territorio Británico del Océano Índico","IO"),
  ("Territorios Australes y Antárticas Franceses","TF"),
  ("Timor Oriental","TL"),
  ("Togo","TG"),
  ("Tokelau","TK"),
  ("Tonga","TO"),
  ("Trinidad y Tobago","TT"),
  ("Tunez","TN"),
  ("Turkmenistán","TM"),
  ("Turquía","TR"),
  ("Tuvalu","TV"),
  ("Ucrania","UA"),
  ("Uganda","UG"),
  ("Uruguay","UY"),
  ("Uzbekistán","UZ"),
  ("Vanuatu","VU"),
  ("Venezuela","VE"),
  ("Vietnam","VN"),
  ("Wallis y Futuna","WF"),
  ("Yemen","YE"),
  ("Yibuti","DJ"),
  ("Zambia","ZM"),
  ("Zimbabue","ZW");

INSERT INTO categorias (nombre, pesoLimiteSuperior,pesoLimiteInferior) VALUES
("peso paja femenil",52,47),
("peso mosca femenil",57,52),
("peso gallo femenil",61,57),
("peso mosca",57,52),
("peso gallo",61,57),
("peso pluma",66,61),
("peso ligero",70,66),
("peso welter",77,70),
("peso medio",84,77),
("peso semipesado",93,84),
("peso pesado",120,93);

INSERT INTO estilosDePelea (nombreDelEstilo, origen) VALUES
("boxeo","reino unido"),
("jiu jitsu brasileño","brasil"),
("lucha olimpica","grecia"),
("kickboxing","japon"),
("kung fu","china"),
("judo","japon"),
("taekwondo","corea"),
("karate","japon"),
("capoeira","brasil"),
("muay thai","tailandia");

INSERT INTO peleadores (Nombre, fechaDeNacimiento,genero,pais_id,categoria_id) VALUES
("Brandon Moreno","1993-12-7","M",141,4),
("Conor McGregor","1988-07-14","M",97,7),
("Alexa Grasso","1993-08-09","F",141,2),
("Max Holloway","1991-12-4","M",65,6),
("Rose Namajunas","1992-06-29","F",65,1),
("Yair Rodriguez","1992-10-6","M",141,6),
("Marlon Vera","1992-12-2","M",57,5),
("Zhang Weili","1989-08-13","F",42,1),
("Derrick Lewis","1985-02-07","M",65,11),
("Amanda Nunes","1988-5-30","F",31,3);

INSERT INTO peleadoresPorPais (peleador_id, pais_id) VALUES
(1,141),
(2,97),
(3,141),
(4,65),
(5,65),
(6,141),
(7,57),
(8,42),
(9,65),
(10,31);

INSERT INTO estilosPorPeleador (peleador_id, estilo_id) VALUES
(1,2),
(1,4),
(2,1),
(2,4),
(3,1),
(4,1),
(5,4),
(6,4),
(6,7),
(7,2),
(7,10),
(8,3),
(8,5),
(9,1),
(9,10),
(10,2),
(10,4);
