CREATE DATABASE IF NOT EXISTS UFC;
USE UFC;

CREATE TABLE paises(
  pais_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  dominio CHAR(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE categorias(
  categoria_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(25) NOT NULL,
  pesoLimiteSuperior INTEGER UNSIGNED NOT NULL
  pesoLimiteInferior INTEGER UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE estilosDePelea(
  estilo_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombreDelEstilo VARCHAR(25) NOT NULL,
  origen CHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE peleadores(
  peleador_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  fechaDeNacimiento DATE NOT NULL
  genero VARCHAR(1) NOT NULL
  pais_id INTEGER UNSIGNED, FOREIGN KEY (pais)
    REFERENCES paises(pais_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
